require "duck_testing/errors"
require "duck_testing/method_call_data"
require "duck_testing/reporter/raise_error"
require "duck_testing/tester"
require "duck_testing/version"
require "duck_testing/violation"
